apiVersion: v1
kind: Pod
metadata:
  name: onai_app
  labels:
    name: onai_app
spec:
  containers:
  - name: onai_app
    image: nginx:latest
    volumeMounts:
      - name: pvc 
        mountPath: /var/www/html
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        protocol: TCP
  volumes:
    - name: pvc 
      persistentVolumeClaim:
        claimName: pvc-1gb



# this will mount the PV at the /var/www/html in the Nginx container allowing it to acess the persistent storage

