# kubectl create secret generic db-password -from-literal=password=mysecretpassword
# this will create a secret called db-password with a single key-value pair "password" with the value "mysecretpassword"

# you can also create a secret from a file such as an SSL certificate 
# kubectl create secret tls tls-certificate -key=key.pem -cert=cert.pem
# this will create a secret called "tls-certificate" with two keys, "tls.key" and "tls.crt" containing the contents of the key.pem and cert.pem files respectively

apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:latest
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secrets
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: secret-volume
      secret:
        secretName: db-password



# this will mount the "db-password" secret as a volume in the pod and make it available at the parth "/etc/secret"
# this application can read the password from the file "etc/secrets/password".

